### PR TITLE
Added resource to block public access to firehose bucket

### PR DESCRIPTION
**Pull request by laurentb4**
Added resource to block public access to firehose bucket

### CODE REVIEW

**Review by asifamirat00 — APPROVED** [review]
lgtm

**Review by smjmoj — APPROVED** [review]
LGTM

**Comment by juddin927** [comment]
I think the bucket policy is blocking all public access on account level, Is there any benefit of applying an explicit block?

**Comment by laurentb4** [comment]
Not needed due to default settings on S3 bucket

**Pull request closed without merging**
